### ISSUE TITLE
Geocodable: updateFrontEndFields should not expect a tabset

### ISSUE THREAD

**Issue by scttw** [symbiote/silverstripe-addressable#55]
In the spec for getFrontEndFields on DataObject the returning object is a note: Always returns a simple field collection without TabSet

The use of the updateCMSFields function inside updateFrontEndFields at line 76 inserts a TabSet which then can't find the tab "Root", as DataObject's  getFrontEndFields function returns a TabSet-less FieldList

Running getFrontEndFields on an Geocodable extended page calss gives the error:
FieldList::addFieldToTab() Tried to add a tab to object 'FieldList' - 'Root' didn't exist.

...at line 76 of Geocodable

**Comment by scttw** [comment]
hey chaps, just wanted to bump this - would be great to get a new release with the supplied PR if it's acceptable.

**Comment by nglasl** [comment]
Hi @scttw, thanks heaps for your contribution here :)

To keep things a little simpler and in the one place, I'm going to close this issue. Please continue any discussion for this over on the PR.
