### ISSUE TITLE
getFrontendFields doesnt seem to be triggered

### ISSUE THREAD

**Issue by phyzical** [symbiote/silverstripe-addressable#60]
so the below in DataObject triggers the updateFrontEndFields in Addressable.
```
public function getFrontEndFields($params = null)
    {
        $untabbedFields = $this->scaffoldFormFields($params);
        $this->extend('updateFrontEndFields', $untabbedFields);

        return $untabbedFields;
    }
```

the issue i am getting is that '$untabbedFields' already contains an 'Address' field (not because of my $db setups... i think) and so the below is never entered
```
public function updateFrontEndFields(FieldList $fields)
    {
        if (!$fields->dataFieldByName("Address")) {
            $fields->merge($this->getAddressFields());
        }
    }
```

any ideas or is this a known bug? thanks~!

**Comment by phyzical** [comment]
the DO i am using is extending Member, so i noticed the fields are added to both member and the extension which might be part of the problem maybe?

**Comment by phyzical** [comment]
bit more FormScaffolder->getFieldList() uses $this->obj->config()->get('db') to build the fields  and as you can see address seems to already be present?
`
‌array (
  'Address' => 'Varchar(255)',
  'Suburb' => 'Varchar(64)',
  'State' => 'Varchar(64)',
  'Postcode' => 'Varchar(10)',
  'Country' => 'Varchar(2)',
  'FirstName' => 'Varchar',
  'Surname' => 'Varchar',
  'Email' => 'Varchar(254)',
  'TempIDHash' => 'Varchar(160)',
  'TempIDExpired' => 'Datetime',
  'Password' => 'Varchar(160)',
  'AutoLoginHash' => 'Varchar(160)',
  'AutoLoginExpired' => 'Datetime',
  'PasswordEncryption' => 'Varchar(50)',
  'Salt' => 'Varchar(50)',
  'PasswordExpiry' => 'Date',
  'LockedOutUntil' => 'Datetime',
  'Locale' => 'Varchar(6)',
  'FailedLoginCount' => 'Int',
)
`

**Comment by stephenmcm** [comment]
Hi @phyzical 
So the logic behind the if check is explained here:
https://github.com/symbiote/silverstripe-addressable/pull/22

I think the intent of the check is still reasonable but the logic is going to always be false as the scaffolder is loading in the DB field already.

The other problem is that this is a breaking change as anyone relying on the current method will have a bad time if we include this.

The best solution is likely moving to a config variable as suggested in the #22 PR and changing `getAddressFields()`  back to a public method. This should allow people to execute the field set up at will and allow for a flexible default.

**Comment by phyzical** [comment]
Thanks for the reply,

i will see if i can pull off what your suggesting, i will post back here with results when i get a chance, feel free to cancel my current PR\ for the time being.

regards,

**Comment by phyzical** [comment]
Hey @stephenmcm finally got a chance to look again, maybe i have another problem i am not aware of? 

i am not providing any additional address fields (that i know of.....), i am applying to the member model.

it returns all the fields as text fields instead of the addressable version because it thinks we have already loaded them?

It just feels that it would always end up skipping getAddressFields() wouldnt it? atleast in its current state.

Do you mind confirming that if you attach addressable to member then call frontendfields do you end up with dropdowns ect. or do you have text fields also?

Thanks in advance!

**Comment by nglasl** [comment]
Closing this as per https://github.com/symbiote/silverstripe-addressable/pull/61. Please let me know if you think it should remain open.
