### ISSUE TITLE
Require silverstripe/cms or silverstripe/framework?

### ISSUE THREAD

**Issue by jinjie** [symbiote/silverstripe-addressable#63]
Is it necessary to require cms? I am building an app that doesn't require the cms component of SilverStripe.

Is framework enough for this module to work?

**Comment by nglasl** [comment]
I believe framework should be enough, but there are likely things that currently depend on the CMS existing. I'm more than happy to accept a PR if you can test and confirm.

**Comment by jinjie** [comment]
PR #64

**Comment by nglasl** [comment]
Closing as per #64.
