### ISSUE TITLE
GeocodeService __CLASS___ returns empty

### ISSUE THREAD

**Issue by CMeldgaard** [symbiote/silverstripe-addressable#65]
In GeocodeService `Config::inst()->get(__CLASS__, 'google_api_key');` return null, becuase `__CLASS__` returns an empty string.

If I use self::class instead it works:

SS version: 4.4
Php version: 7.2

**Comment by stephenmcm** [comment]
Hi @CMeldgaard,  
Can I get some example/test code, please? `__CLASS__` is a PHP built-in so if it's not working, we've hit an interesting edge case. It's more likely that the config yml has a typo.   
I'm assuming we're talking about this line here:  
https://github.com/symbiote/silverstripe-addressable/blob/master/src/GoogleGeocodeService.php#L46
