### ISSUE TITLE
GoogleGeocodeService will never find the Google Maps API key in the Config

### ISSUE THREAD

**Issue by Lightnicus** [symbiote/silverstripe-addressable#68]
This code starting on line 46 in GoogleGeocodeService.php: 

>         $key = getenv('GOOGLE_API_KEY')
>            ?? Config::inst()->get(__CLASS__, 'google_api_key')
>            ?? Config::inst()->get('Symbiote\\Addressable\\GeocodeService', 'google_api_key');

does not work I believe. getenv() always returns either a string or false. Using the null coalesce operator ?? therefore will never query the Config API even if there's no key set in the environment.

**Comment by scttw** [comment]
This has been updated on master, but was never pushed into a release/branch.  Is it possible to have a new release added for this fix?
