### ISSUE TITLE
5.0.4 tag/ version

### ISSUE THREAD

**Issue by hubertusanton** [symbiote/silverstripe-addressable#71]
Hi,

I'm having issues with version 5.0.3 in the way the api keys are set and get by getenv( 

Are you planning to release the changes https://github.com/symbiote/silverstripe-addressable/compare/5.0.3...master as 5.0.4?

Thanks,

Bart

**Comment by JamesDPC** [comment]
Ditto, that'd be nice to have it tagged 🙏🏽

**Comment by JamesDPC** [comment]
Somewhat related to #72 - this could go out as a 5.0.4 and the guzzle/SS 4.11.0 change as a 6.0 - @nyeholt what do you think ?

**Comment by hubertusanton** [comment]
hi, any decision taken for this issue?
