### ISSUE TITLE
Silverstripe 4.11.0 requires Guzzle 7

### ISSUE THREAD

**Issue by jules0x** [symbiote/silverstripe-addressable#72]
It appears that sites using this module cannot upgrade to the latest framework version as the guzzle requirements conflicts.

**Addressable 5.0.3**
```
{
    "name": "symbiote/silverstripe-addressable",
    "require": {
        "guzzlehttp/guzzle": "^5.3.1|^6.2.1"
```

**Framework 4.11.0**
```
{
    "name": "silverstripe/framework",
    "require": {
        "guzzlehttp/guzzle": "^7",
        "guzzlehttp/psr7": "^2",
```

**Comment by JamesDPC** [comment]
Hi @nyeholt - any chance of having a look at #73 and adding thoughts?

**Comment by RVXD** [comment]
Any updates on this issue?

**Comment by jalamanderman** [comment]
Hi there, this also an issue for me. Any updates?

**Comment by RVXD** [comment]
Please allow for guzzle 7, we need CMS 4.11
